groups:
  - name: crawler_alerts
    rules:
      # Queue depth alerts
      - alert: CrawlerQueueDepthHigh
        expr: crawler_queue_depth > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Crawler queue depth is high"
          description: "Queue depth has been above 1000 for 5 minutes. Current value: {{ $value }}"

      - alert: CrawlerQueueDepthCritical
        expr: crawler_queue_depth > 5000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Crawler queue depth is critical"
          description: "Queue depth has been above 5000 for 2 minutes. Current value: {{ $value }}"

      # Consumer lag alerts
      - alert: CrawlerConsumerLagHigh
        expr: crawler_consumer_lag > 500
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Crawler consumer lag is high"
          description: "Consumer lag has been above 500 for 5 minutes. Current value: {{ $value }}"

      - alert: CrawlerConsumerLagCritical
        expr: crawler_consumer_lag > 2000
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Crawler consumer lag is critical"
          description: "Consumer lag has been above 2000 for 2 minutes. Current value: {{ $value }}"

      # Processing rate alerts
      - alert: CrawlerProcessingRateLow
        expr: rate(crawler_pages_total[5m]) < 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Crawler processing rate is low"
          description: "Processing rate has been below 1 page per second for 10 minutes. Current rate: {{ $value }} pages/sec"

      - alert: CrawlerProcessingRateCritical
        expr: rate(crawler_pages_total[5m]) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Crawler processing rate is critical"
          description: "Processing rate has been below 0.1 pages per second for 5 minutes. Current rate: {{ $value }} pages/sec"

      # Error rate alerts
      - alert: CrawlerErrorRateHigh
        expr: rate(crawler_errors_total[5m]) / rate(crawler_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Crawler error rate is high"
          description: "Error rate has been above 10% for 5 minutes. Current rate: {{ $value | humanizePercentage }}"

      - alert: CrawlerErrorRateCritical
        expr: rate(crawler_errors_total[5m]) / rate(crawler_requests_total[5m]) > 0.3
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Crawler error rate is critical"
          description: "Error rate has been above 30% for 2 minutes. Current rate: {{ $value | humanizePercentage }}"

      # Latency alerts
      - alert: CrawlerFetchLatencyHigh
        expr: histogram_quantile(0.95, rate(crawler_fetch_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Crawler fetch latency is high"
          description: "95th percentile fetch latency has been above 5 seconds for 5 minutes. Current latency: {{ $value }}s"

      - alert: CrawlerProcessLatencyHigh
        expr: histogram_quantile(0.95, rate(crawler_process_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Crawler processing latency is high"
          description: "95th percentile processing latency has been above 10 seconds for 5 minutes. Current latency: {{ $value }}s"

      # Cache performance alerts
      - alert: CrawlerCacheHitRateLow
        expr: rate(crawler_cache_hits_total[5m]) / (rate(crawler_cache_hits_total[5m]) + rate(crawler_cache_misses_total[5m])) < 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Crawler cache hit rate is low"
          description: "Cache hit rate has been below 50% for 15 minutes. Current rate: {{ $value | humanizePercentage }}"

      # Priority alerts
      - alert: CrawlerPriorityScoreLow
        expr: crawler_priority_avg < 0.3
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Crawler average priority score is low"
          description: "Average priority score has been below 0.3 for 30 minutes. Current score: {{ $value }}"

      # Active crawls alerts
      - alert: CrawlerActiveCrawlsHigh
        expr: crawler_active_crawls > 8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Number of active crawls is high"
          description: "Number of active crawls has been above 8 for 5 minutes. Current count: {{ $value }}" 