version: '3.8'

name: concept-dictionary

networks:
  backend:
    name: lumina-system_backend
    external: true

services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --protected-mode yes --requirepass 02211998 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '>/dev/tcp/localhost/6333'"]
      interval: 10s
      timeout: 3s
      retries: 3

  concept-dictionary:
    build:
      context: .
      dockerfile: services/concept-dictionary/Dockerfile
    ports:
      - "8828:8828"
    environment:
      - REDIS_URL=redis://:02211998@redis:6379
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8828/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  qdrant_data: 