version: '3.8'

services:
  crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8400:8400"
    environment:
      - REDIS_URL=redis://redis:6379
      - GRAPH_API_URL=http://graph-api:8200
      - WIKI_SEARCH_DEPTH=2
      - WIKI_MAX_RESULTS=10
      - TRAINING_DATA_PATH=/app/training_data/graph (1).json
      - PROCESS_INTERVAL=3600  # Process graph every hour
    volumes:
      - ../training_data:/app/training_data
    depends_on:
      redis:
        condition: service_healthy
      graph-api:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  graph-api:
    image: neo4j:4.4
    ports:
      - "8200:7474"
      - "7687:7687"  # Bolt protocol port
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - graph_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
  graph_data:

networks:
  default:
    name: crawler_network
    driver: bridge 