server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /var/log/app/**/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            msg: message
            trace_id: trace_id
            request_id: request_id
      - labels:
          level:
          service:
          trace_id:
          request_id:

  - job_name: graph-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: graph-api
          service: graph-api
          __path__: /var/log/app/graph-api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            msg: message
            trace_id: trace_id
            request_id: request_id
      - labels:
          level:
          service:
          trace_id:
          request_id:

  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          service: redis
          __path__: /var/log/app/redis/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            msg: message
            trace_id: trace_id
            request_id: request_id
      - labels:
          level:
          service:
          trace_id:
          request_id:

  - job_name: qdrant
    static_configs:
      - targets:
          - localhost
        labels:
          job: qdrant
          service: qdrant
          __path__: /var/log/app/qdrant/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            msg: message
            trace_id: trace_id
            request_id: request_id
      - labels:
          level:
          service:
          trace_id:
          request_id:

  - job_name: test-runner
    static_configs:
      - targets:
          - localhost
        labels:
          job: test-runner
          service: test-runner
          __path__: /var/log/app/test-runner/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            msg: message
            trace_id: trace_id
            request_id: request_id
      - labels:
          level:
          service:
          trace_id:
          request_id: 