name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test
    
    - name: Run Cypress stubbed tests
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:3000'
        command: npm run cypress:stubbed
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    
    - name: Run Cypress live-backend tests
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: docker compose -f cypress/docker-compose.ci.yml up --build -d
        wait-on: 'http://localhost:3000'
        command: npm run cypress:live
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-results
        path: |
          cypress/screenshots
          coverage
        retention-days: 7
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage
        retention-days: 7
    
    - name: Notify Slack on failure
      if: failure()
      uses: slackapi/slack-github-action@v1.25.0
      with:
        channel-id: 'monitoring'
        slack-message: |
          :x: Tests failed in ${{ github.repository }}#${{ github.run_number }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 