name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Lumina would this affect?
      options:
        - Backend (lumina_core)
        - Frontend (ui)
        - Operations (ops)
        - Documentation
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How would this feature benefit users?
      placeholder: Describe the impact this feature would have on users and the project.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any other information that might be relevant 