version: '3.8'

services:
  concept-dictionary:
    build:
      context: ./concept-dict
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONCEPT_DICT_API_KEY=${GRAPH_API_KEY:-changeme}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8400:8400"
    environment:
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      - GRAPH_API_URL=http://graph-api:8200
      - CONCEPT_DICT_URL=http://concept-dictionary:8000
      - GRAPH_API_KEY=${GRAPH_API_KEY:-changeme}
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - WIKI_SEARCH_DEPTH=2
      - WIKI_MAX_RESULTS=10
      - TRAINING_DATA_PATH=/app/data/graph.json
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - qdrant
      - concept-dictionary

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  graph-api:
    image: neo4j:4.4
    ports:
      - "8200:8200"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data

volumes:
  redis_data:
  qdrant_data:
  neo4j_data:

networks:
  default:
    name: crawler_network
    driver: bridge 