name: Lumina Backup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to backup'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  backup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Run backup
      run: |
        cd ops
        chmod +x freeze_and_push.sh verify_freeze.sh
        ./freeze_and_push.sh
      env:
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    
    - name: Upload backup URL
      uses: actions/upload-artifact@v4
      with:
        name: backup-url
        path: ops/last_backup_url.txt
        retention-days: 30 